export const WHATSAPP_NUMBER = "573102108900"; // +57 310 210 8900
export const INSTAGRAM = "escapate.cuc";
export const EMAIL = "reservas@escapate.tours";
// Access key de Web3Forms. Se lee de la env var NEXT_PUBLIC_WEB3FORMS_KEY (ver .env.example).
// Ojo: en un export estático NO es secreta — termina en el bundle del navegador. La env var
// es solo higiene (no commitear, rotar fácil). El blindaje real va en el panel de Web3Forms:
// restringir la key al dominio escapate.tours + captcha/honeypot.
export const WEB3FORMS_KEY = process.env.NEXT_PUBLIC_WEB3FORMS_KEY ?? "";

/** Enlace de WhatsApp con un mensaje opcional prellenado. */
export function waLink(message?: string) {
  const base = `https://wa.me/${WHATSAPP_NUMBER}`;
  return message ? `${base}?text=${encodeURIComponent(message)}` : base;
}

/**
 * Deep link de Google Maps para "Cómo llegar" (abre el pin del local).
 * Distinto de BUSINESS.maps, que alimenta el `hasMap` del JSON-LD.
 */
export const MAPS_DIRECTIONS_URL = "https://maps.app.goo.gl/YnDfD9VLLPeg2bBYA";

/**
 * Datos del negocio — fuente única de verdad para el structured data (SEO local)
 * y para la UI (NAP visible). Que el JSON-LD y lo que se ve en la página coincidan
 * es justo lo que Google premia para el negocio local / Google Maps.
 */
export const BUSINESS = {
  name: "Escápate",
  legalName: "Escápate · Agencia de Viajes",
  url: "https://escapate.tours",
  // Mismo correo que se muestra en el footer: el NAP visible y el structured data
  // tienen que coincidir, si no el SEO local castiga la discrepancia.
  email: EMAIL,
  phone: "+573102108900",
  priceRange: "$$",
  currency: "COP",
  address: {
    street: "Local 2, Autopista Internacional Vía Antigua Boconó K1-046",
    locality: "Cúcuta",
    region: "Norte de Santander",
    country: "CO",
    // Cadena lista para mostrar (NAP visible == structured data).
    full: "Local 2, Autopista Internacional Vía Antigua Boconó K1-046, Cúcuta, Norte de Santander",
  },
  // Coordenadas del pin. Alimentan el GeoCoordinates del JSON-LD y el mapa embebido
  // de Gallery — un solo dato para los dos, que es justo lo que Google contrasta.
  geo: { lat: 7.853932, lng: -72.4663327 } as { lat: number; lng: number } | null,
  maps: "https://share.google/4xzchCjiY6NQzaqlN",
  hours: {
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    opens: "08:00",
    closes: "18:00",
  },
  sameAs: [`https://www.instagram.com/${INSTAGRAM}`],
  logo: "/logo/escapate-transparent.png",
  photos: ["/renders/local-reception.jpg", "/renders/local-lounge.jpg"],
};

export const content = {
  es: {
    wa: { hello: "¡Hola! Quisiera información sobre sus planes de viaje." },
    nav: {
      links: [
        { id: "destinos", label: "Destinos" },
        { id: "nosotros", label: "Nosotros" },
        { id: "servicios", label: "Servicios" },
        { id: "contacto", label: "Contacto" },
      ],
      cta: "Cotizar",
      skip: "Saltar al contenido",
    },
    hero: {
      eyebrow: "Agencia de viajes · Cúcuta",
      agency: "Agencia de viajes",
      titleA: "Tu viaje",
      titleB: "empieza",
      titleAccent: "aquí",
      subtitle:
        "Gira el mundo, elige un destino y nosotros armamos la escapada completa. Vuelos, hoteles y planes pensados a tu medida.",
      ctaPrimary: "Planear mi viaje",
      ctaSecondary: "Explorar destinos",
      dragHint: "arrastra para girar el mundo",
      passenger: "Pasajero",
      route: "Cúcuta → el mundo",
    },
    destinos: {
      eyebrow: "Destinos",
      title: "A dónde te llevamos",
      note: "Precios de referencia por persona. Cuéntanos tus fechas y armamos el plan exacto.",
      perPerson: "por persona",
      groups: { colombia: "Colombia", internacional: "Internacional" },
      items: [
        { id: "cartagena", group: "colombia", name: "Cartagena", region: "Caribe colombiano", nights: "4 noches", price: "desde $890.000", img: "/destinos/cartagena.webp" },
        { id: "san-andres", group: "colombia", name: "San Andrés", region: "Mar de siete colores", nights: "5 noches", price: "desde $1.250.000", img: "/destinos/san-andres.webp" },
        { id: "santa-marta", group: "colombia", name: "Santa Marta", region: "Tayrona y Caribe", nights: "4 noches", price: "desde $760.000", img: "/destinos/santa-marta.webp" },
        { id: "eje-cafetero", group: "colombia", name: "Eje Cafetero", region: "Valle de Cocora", nights: "3 noches", price: "desde $640.000", img: "/destinos/eje-cafetero.webp" },
        { id: "cancun", group: "internacional", name: "Cancún", region: "Riviera Maya", nights: "6 noches", price: "desde $3.100.000", img: "/destinos/cancun.webp" },
        { id: "punta-cana", group: "internacional", name: "Punta Cana", region: "Caribe", nights: "6 noches", price: "desde $3.400.000", img: "/destinos/punta-cana.webp" },
        { id: "espana", group: "internacional", name: "España", region: "Madrid · Sevilla", nights: "8 noches", price: "desde $5.400.000", img: "/destinos/espana.webp" },
        { id: "europa", group: "internacional", name: "Europa", region: "París · multidestino", nights: "10 noches", price: "desde $7.200.000", img: "/destinos/europa.webp" },
      ],
      // Destinos que solo viven como pin en el globo: todavía no tienen paquete armado,
      // por eso no llevan precio ni noches (la card muestra el país en su lugar). El
      // botón de cotizar sí aparece: justo son los que necesitan que el cliente pregunte.
      // El id tiene que existir en DESTINO_GEO y tener foto en /destinos/globo/<id>.webp.
      more: [
        { id: "rome", name: "Roma", region: "Italia" },
        { id: "london", name: "Londres", region: "Reino Unido" },
        { id: "barcelona", name: "Barcelona", region: "España" },
        { id: "lisbon", name: "Lisboa", region: "Portugal" },
        { id: "amsterdam", name: "Ámsterdam", region: "Países Bajos" },
        { id: "venice", name: "Venecia", region: "Italia" },
        { id: "santorini", name: "Santorini", region: "Grecia" },
        { id: "istanbul", name: "Estambul", region: "Turquía" },
        { id: "prague", name: "Praga", region: "República Checa" },
        { id: "vienna", name: "Viena", region: "Austria" },
        { id: "athens", name: "Atenas", region: "Grecia" },
        { id: "swiss-alps", name: "Alpes Suizos", region: "Suiza" },
        { id: "new-york", name: "Nueva York", region: "Estados Unidos" },
        { id: "miami", name: "Miami", region: "Estados Unidos" },
        { id: "orlando", name: "Orlando", region: "Estados Unidos" },
        { id: "los-angeles", name: "Los Ángeles", region: "Estados Unidos" },
        { id: "las-vegas", name: "Las Vegas", region: "Estados Unidos" },
        { id: "toronto", name: "Toronto", region: "Canadá" },
        { id: "mexico-city", name: "Ciudad de México", region: "México" },
        { id: "rio-de-janeiro", name: "Río de Janeiro", region: "Brasil" },
        { id: "buenos-aires", name: "Buenos Aires", region: "Argentina" },
        { id: "lima", name: "Lima", region: "Perú" },
        { id: "cusco", name: "Cusco", region: "Perú · Machu Picchu" },
        { id: "santiago", name: "Santiago", region: "Chile" },
        { id: "aruba", name: "Aruba", region: "Caribe" },
        { id: "havana", name: "La Habana", region: "Cuba" },
        { id: "panama-city", name: "Ciudad de Panamá", region: "Panamá" },
        { id: "san-jose-cr", name: "San José", region: "Costa Rica" },
        { id: "galapagos", name: "Galápagos", region: "Ecuador" },
        { id: "dubai", name: "Dubái", region: "Emiratos Árabes Unidos" },
        { id: "tokyo", name: "Tokio", region: "Japón" },
        { id: "kyoto", name: "Kioto", region: "Japón" },
        { id: "bangkok", name: "Bangkok", region: "Tailandia" },
        { id: "bali", name: "Bali", region: "Indonesia" },
        { id: "singapore", name: "Singapur", region: "Singapur" },
        { id: "phuket", name: "Phuket", region: "Tailandia" },
        { id: "hong-kong", name: "Hong Kong", region: "China" },
        { id: "maldives", name: "Maldivas", region: "Océano Índico" },
        { id: "cape-town", name: "Ciudad del Cabo", region: "Sudáfrica" },
        { id: "marrakech", name: "Marrakech", region: "Marruecos" },
        { id: "cairo", name: "El Cairo", region: "Egipto" },
        { id: "sydney", name: "Sídney", region: "Australia" },
      ],
    },
    about: {
      eyebrow: "Quiénes somos",
      title: "No vendemos viajes. Diseñamos recuerdos.",
      body: "Somos un equipo de Cúcuta apasionado por viajar. Creemos en el trato cercano: te escuchamos, entendemos cómo sueñas tu escapada y nos encargamos de cada detalle para que tú solo te preocupes por disfrutar.",
      stats: [
        { n: "+10", label: "años de experiencia" },
        { n: "+40", label: "destinos" },
        { n: "100%", label: "acompañamiento" },
      ],
    },
    services: {
      eyebrow: "Lo que hacemos por ti",
      title: "Todo en un solo lugar",
      items: [
        { title: "Paquetes a tu medida", desc: "Vuelo, hotel, traslados y planes en una sola cotización clara." },
        { title: "Asesoría experta", desc: "Te guiamos paso a paso, desde la idea hasta la maleta lista." },
        { title: "Soporte total", desc: "Acompañamiento antes, durante y después de tu viaje." },
        { title: "Lunas de miel y grupos", desc: "Experiencias especiales para parejas, familias y empresas." },
      ],
    },
    why: {
      eyebrow: "Por qué Escápate",
      title: "Viajar tranquilo se siente distinto",
      board: "Tablero de salidas",
      onTime: "A tiempo",
      points: [
        "Atención personalizada, cara a cara o por WhatsApp.",
        "Precios transparentes, sin sorpresas de último minuto.",
        "Aliados confiables en aerolíneas y hoteles.",
        "Planes flexibles que se adaptan a tu presupuesto.",
      ],
    },
    gallery: {
      eyebrow: "El local",
      title: "Ven a soñar tu viaje en persona",
      body: "Un espacio pensado para inspirarte. Te esperamos en el centro de Cúcuta.",
      directions: "Cómo llegar",
    },
    testimonials: {
      eyebrow: "Lo que dicen",
      title: "Viajeros que ya se escaparon",
      stars: "5 de 5 estrellas",
      items: [
        { quote: "Nos armaron la luna de miel perfecta. Cada detalle salió tal como lo soñamos.", name: "Laura & Andrés", role: "Cancún 2025" },
        { quote: "Súper atentos por WhatsApp a cualquier hora. Viajé tranquila y sin estrés.", name: "Daniela M.", role: "España 2025" },
        { quote: "Mejor precio que buscando por mi cuenta, y con todo resuelto. Repetiré.", name: "Carlos R.", role: "San Andrés 2024" },
      ],
    },
    contact: {
      eyebrow: "Contacto",
      title: "¿Listo para volar?",
      subtitle: "Escríbenos por WhatsApp o déjanos tus datos y te contactamos hoy mismo.",
      whatsapp: "Hablar por WhatsApp",
      address: BUSINESS.address.full,
      hours: "Lun a Sáb · 8:00 a.m. – 6:00 p.m.",
    },
    // Textos del globo 3D. Los marcadores viven dentro del <Canvas>, que corre en
    // otro reconciliador: el contexto de React NO entra ahí, así que estas cadenas
    // se pasan como props (ver GlobeLabels en globe/Globe.tsx).
    globe: {
      explore: "Explorar",
      destinations: "Destinos",
      hint: "Rueda o pellizca para acercar · arrastra para girar",
      close: "Cerrar",
      closeMap: "Cerrar el mapa",
      inArea: "destinos en esta zona, abrir lista",
      viewOnGlobe: "Ver en el globo",
      controls: "Controles del globo",
      showControls: "Mostrar controles del globo",
      hideControls: "Ocultar controles del globo",
      rotateLeft: "Girar el globo a la izquierda",
      rotateRight: "Girar el globo a la derecha",
      rotateUp: "Girar el globo hacia arriba",
      rotateDown: "Girar el globo hacia abajo",
      pause: "Pausar la rotación",
      resume: "Reanudar la rotación",
      recenter: "Recentrar el globo",
      zoomIn: "Acercar el globo",
      zoomOut: "Alejar el globo",
    },
    quote: {
      eyebrow: "Cotiza tu viaje",
      prefillNote: "Interesado en el paquete",
      title: "Arma tu escapada",
      from: "Ciudad de salida",
      dest: "Destino / Tour",
      passengers: "Pasajeros",
      adults: "Adultos",
      children: "Niños",
      seniors: "Tercera edad",
      phone: "Celular",
      emailField: "Correo electrónico",
      more: "Más detalles (opcional)",
      notes: "Notas u observaciones",
      notesPh: "Cuéntanos cualquier detalle extra…",
      hasDates: "¿Ya tienes fechas?",
      month: "Mes tentativo",
      monthPh: "Elige un mes",
      departure: "Salida",
      returnLabel: "Regreso",
      lodging: "Hospedaje",
      hotel: "Categoría del hotel",
      plan: "Tipo de plan",
      prefs: "Preferencias",
      otherPrefPh: "Otra preferencia…",
      required: "Completa este campo",
      invalidPhone: "Ingresa un celular válido.",
      invalidEmail: "Correo inválido. Revisa el formato (ej. nombre@correo.com).",
      invalidDates: "El regreso no puede ser antes de la salida.",
      days: "Días",
      daysUnit: "días",
      name: "Tu nombre",
      people: "personas",
      whatsapp: "Cotizar por WhatsApp",
      email: "Enviar al correo",
      ok: "¡Gracias! Te enviaremos la cotización muy pronto.",
      err: "Algo salió mal. Escríbenos por WhatsApp.",
      cities: ["Cúcuta", "Bogotá", "Medellín", "Cali", "Bucaramanga", "Otra ciudad"],
      tours: ["Cartagena", "San Andrés", "Santa Marta", "Eje Cafetero", "Cancún", "Punta Cana", "Panamá", "España", "Europa", "Aún no lo decido"],
      months: ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],
      hotelOptions: ["3★","4★","5★","Apartamento","Sin preferencia"],
      planOptions: ["Solo alojamiento","Desayuno incluido","Todo incluido"],
      prefsOptions: ["Frente al mar","Centro de la ciudad","Cerca al aeropuerto"],
      msg: {
        intro: "Hola, quiero cotizar un viaje:",
        from: "Salida",
        dest: "Destino",
        pax: "Pasajeros",
        days: "Días",
        name: "Nombre",
        phone: "Celular",
        email: "Correo",
        month: "Mes",
        departure: "Salida",
        ret: "Regreso",
        hotel: "Hotel",
        plan: "Plan",
        prefs: "Preferencias",
        notes: "Notas",
      },
    },
    footer: {
      tagline: "Tu viaje empieza aquí.",
      rights: "Todos los derechos reservados.",
      madeIn: "Hecho con cariño en Cúcuta.",
    },
  },

  en: {
    wa: { hello: "Hi! I'd like information about your travel plans." },
    nav: {
      links: [
        { id: "destinos", label: "Destinations" },
        { id: "nosotros", label: "About" },
        { id: "servicios", label: "Services" },
        { id: "contacto", label: "Contact" },
      ],
      cta: "Get a quote",
      skip: "Skip to content",
    },
    hero: {
      eyebrow: "Travel agency · Cúcuta",
      agency: "Travel agency",
      titleA: "Your journey",
      titleB: "starts",
      titleAccent: "here",
      subtitle:
        "Spin the globe, pick a destination and we'll handle the whole escape. Flights, hotels and plans tailored to you.",
      ctaPrimary: "Plan my trip",
      ctaSecondary: "Explore destinations",
      dragHint: "drag to spin the globe",
      passenger: "Passenger",
      route: "Cúcuta → the world",
    },
    destinos: {
      eyebrow: "Destinations",
      title: "Where we take you",
      note: "Reference prices per person. Tell us your dates and we'll build the exact plan.",
      perPerson: "per person",
      groups: { colombia: "Colombia", internacional: "International" },
      items: [
        { id: "cartagena", group: "colombia", name: "Cartagena", region: "Colombian Caribbean", nights: "4 nights", price: "from $890,000", img: "/destinos/cartagena.webp" },
        { id: "san-andres", group: "colombia", name: "San Andrés", region: "Seven-color sea", nights: "5 nights", price: "from $1,250,000", img: "/destinos/san-andres.webp" },
        { id: "santa-marta", group: "colombia", name: "Santa Marta", region: "Tayrona & Caribbean", nights: "4 nights", price: "from $760,000", img: "/destinos/santa-marta.webp" },
        { id: "eje-cafetero", group: "colombia", name: "Coffee Region", region: "Cocora Valley", nights: "3 nights", price: "from $640,000", img: "/destinos/eje-cafetero.webp" },
        { id: "cancun", group: "internacional", name: "Cancún", region: "Riviera Maya", nights: "6 nights", price: "from $3,100,000", img: "/destinos/cancun.webp" },
        { id: "punta-cana", group: "internacional", name: "Punta Cana", region: "Caribbean", nights: "6 nights", price: "from $3,400,000", img: "/destinos/punta-cana.webp" },
        { id: "espana", group: "internacional", name: "Spain", region: "Madrid · Seville", nights: "8 nights", price: "from $5,400,000", img: "/destinos/espana.webp" },
        { id: "europa", group: "internacional", name: "Europe", region: "Paris · multi-city", nights: "10 nights", price: "from $7,200,000", img: "/destinos/europa.webp" },
      ],
      // Ver la nota del bloque ES: destinos sin paquete armado, solo pin + foto.
      more: [
        { id: "rome", name: "Rome", region: "Italy" },
        { id: "london", name: "London", region: "United Kingdom" },
        { id: "barcelona", name: "Barcelona", region: "Spain" },
        { id: "lisbon", name: "Lisbon", region: "Portugal" },
        { id: "amsterdam", name: "Amsterdam", region: "Netherlands" },
        { id: "venice", name: "Venice", region: "Italy" },
        { id: "santorini", name: "Santorini", region: "Greece" },
        { id: "istanbul", name: "Istanbul", region: "Turkey" },
        { id: "prague", name: "Prague", region: "Czech Republic" },
        { id: "vienna", name: "Vienna", region: "Austria" },
        { id: "athens", name: "Athens", region: "Greece" },
        { id: "swiss-alps", name: "Swiss Alps", region: "Switzerland" },
        { id: "new-york", name: "New York", region: "United States" },
        { id: "miami", name: "Miami", region: "United States" },
        { id: "orlando", name: "Orlando", region: "United States" },
        { id: "los-angeles", name: "Los Angeles", region: "United States" },
        { id: "las-vegas", name: "Las Vegas", region: "United States" },
        { id: "toronto", name: "Toronto", region: "Canada" },
        { id: "mexico-city", name: "Mexico City", region: "Mexico" },
        { id: "rio-de-janeiro", name: "Rio de Janeiro", region: "Brazil" },
        { id: "buenos-aires", name: "Buenos Aires", region: "Argentina" },
        { id: "lima", name: "Lima", region: "Peru" },
        { id: "cusco", name: "Cusco", region: "Peru · Machu Picchu" },
        { id: "santiago", name: "Santiago", region: "Chile" },
        { id: "aruba", name: "Aruba", region: "Caribbean" },
        { id: "havana", name: "Havana", region: "Cuba" },
        { id: "panama-city", name: "Panama City", region: "Panama" },
        { id: "san-jose-cr", name: "San José", region: "Costa Rica" },
        { id: "galapagos", name: "Galápagos", region: "Ecuador" },
        { id: "dubai", name: "Dubai", region: "United Arab Emirates" },
        { id: "tokyo", name: "Tokyo", region: "Japan" },
        { id: "kyoto", name: "Kyoto", region: "Japan" },
        { id: "bangkok", name: "Bangkok", region: "Thailand" },
        { id: "bali", name: "Bali", region: "Indonesia" },
        { id: "singapore", name: "Singapore", region: "Singapore" },
        { id: "phuket", name: "Phuket", region: "Thailand" },
        { id: "hong-kong", name: "Hong Kong", region: "China" },
        { id: "maldives", name: "Maldives", region: "Indian Ocean" },
        { id: "cape-town", name: "Cape Town", region: "South Africa" },
        { id: "marrakech", name: "Marrakesh", region: "Morocco" },
        { id: "cairo", name: "Cairo", region: "Egypt" },
        { id: "sydney", name: "Sydney", region: "Australia" },
      ],
    },
    about: {
      eyebrow: "About us",
      title: "We don't sell trips. We design memories.",
      body: "We're a team from Cúcuta who love to travel. We believe in a personal touch: we listen, understand how you dream your escape, and take care of every detail so all you have to do is enjoy.",
      stats: [
        { n: "+10", label: "years of experience" },
        { n: "+40", label: "destinations" },
        { n: "100%", label: "support" },
      ],
    },
    services: {
      eyebrow: "What we do for you",
      title: "Everything in one place",
      items: [
        { title: "Tailor-made packages", desc: "Flight, hotel, transfers and plans in one clear quote." },
        { title: "Expert advice", desc: "We guide you step by step, from the idea to a packed suitcase." },
        { title: "Full support", desc: "We're with you before, during and after your trip." },
        { title: "Honeymoons & groups", desc: "Special experiences for couples, families and companies." },
      ],
    },
    why: {
      eyebrow: "Why Escápate",
      title: "Traveling with peace of mind feels different",
      board: "Departures board",
      onTime: "On time",
      points: [
        "Personal attention, face to face or over WhatsApp.",
        "Transparent prices, no last-minute surprises.",
        "Trusted airline and hotel partners.",
        "Flexible plans that fit your budget.",
      ],
    },
    gallery: {
      eyebrow: "Our space",
      title: "Come dream your trip in person",
      body: "A space made to inspire you. Come see us in downtown Cúcuta.",
      directions: "Get directions",
    },
    testimonials: {
      eyebrow: "What they say",
      title: "Travelers who already escaped",
      stars: "5 out of 5 stars",
      items: [
        { quote: "They built the perfect honeymoon. Every detail turned out just as we dreamed.", name: "Laura & Andrés", role: "Cancún 2025" },
        { quote: "Super responsive on WhatsApp at any hour. I traveled relaxed and stress-free.", name: "Daniela M.", role: "Spain 2025" },
        { quote: "Better price than booking on my own, with everything sorted. I'll be back.", name: "Carlos R.", role: "San Andrés 2024" },
      ],
    },
    contact: {
      eyebrow: "Contact",
      title: "Ready to fly?",
      subtitle: "Message us on WhatsApp or leave your details and we'll reach out today.",
      whatsapp: "Chat on WhatsApp",
      address: BUSINESS.address.full,
      hours: "Mon to Sat · 8:00 a.m. – 6:00 p.m.",
    },
    globe: {
      explore: "Explore",
      destinations: "Destinations",
      hint: "Scroll or pinch to zoom · drag to spin",
      close: "Close",
      closeMap: "Close the map",
      inArea: "destinations in this area, open list",
      viewOnGlobe: "View on the globe",
      controls: "Globe controls",
      showControls: "Show globe controls",
      hideControls: "Hide globe controls",
      rotateLeft: "Spin the globe left",
      rotateRight: "Spin the globe right",
      rotateUp: "Spin the globe up",
      rotateDown: "Spin the globe down",
      pause: "Pause the rotation",
      resume: "Resume the rotation",
      recenter: "Recenter the globe",
      zoomIn: "Zoom in",
      zoomOut: "Zoom out",
    },
    quote: {
      eyebrow: "Get a quote",
      prefillNote: "Interested in the package",
      title: "Build your escape",
      from: "Departure city",
      dest: "Destination / Tour",
      passengers: "Passengers",
      adults: "Adults",
      children: "Children",
      seniors: "Seniors",
      phone: "Phone",
      emailField: "Email",
      more: "More details (optional)",
      notes: "Notes or comments",
      notesPh: "Tell us any extra details…",
      hasDates: "Do you have dates?",
      month: "Tentative month",
      monthPh: "Choose a month",
      departure: "Departure",
      returnLabel: "Return",
      lodging: "Lodging",
      hotel: "Hotel category",
      plan: "Plan type",
      prefs: "Preferences",
      otherPrefPh: "Other preference…",
      required: "Please complete this field",
      invalidPhone: "Enter a valid phone number.",
      invalidEmail: "Invalid email. Check the format (e.g. name@email.com).",
      invalidDates: "The return date can't be before the departure date.",
      days: "Days",
      daysUnit: "days",
      name: "Your name",
      people: "people",
      whatsapp: "Quote on WhatsApp",
      email: "Send by email",
      ok: "Thank you! We'll send your quote very soon.",
      err: "Something went wrong. Message us on WhatsApp.",
      cities: ["Cúcuta", "Bogotá", "Medellín", "Cali", "Bucaramanga", "Other city"],
      tours: ["Cartagena", "San Andrés", "Santa Marta", "Coffee Region", "Cancún", "Punta Cana", "Panama", "Spain", "Europe", "Not sure yet"],
      months: ["January","February","March","April","May","June","July","August","September","October","November","December"],
      hotelOptions: ["3★","4★","5★","Apartment","No preference"],
      planOptions: ["Room only","Breakfast included","All inclusive"],
      prefsOptions: ["Beachfront","City center","Near the airport"],
      msg: {
        intro: "Hi, I'd like a quote for a trip:",
        from: "Departure",
        dest: "Destination",
        pax: "Passengers",
        days: "Days",
        name: "Name",
        phone: "Phone",
        email: "Email",
        month: "Month",
        departure: "Departure",
        ret: "Return",
        hotel: "Hotel",
        plan: "Plan",
        prefs: "Preferences",
        notes: "Notes",
      },
    },
    footer: {
      tagline: "Your journey starts here.",
      rights: "All rights reserved.",
      madeIn: "Made with love in Cúcuta.",
    },
  },
} as const;

export type Lang = keyof typeof content;
export type Dict = (typeof content)[Lang];
